# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorited_tweet', to='api.Favorite'),
        ),
    ]
