# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tweet_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tweet', to='api.Tweet')),
                ('reply_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_tweet', to='api.Tweet')),
            ],
        ),
    ]
