# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='base_tweet',
            new_name='base',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_tweet',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply_twee', to='api.Tweet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='reply_tweet', to='api.Reply'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='base_tweet', to='api.Reply'),
        ),
    ]
