# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180320_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='child',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
